### ISSUE TITLE
[FEAT]: add prefers-reduced-motion media query

### ISSUE THREAD

**Issue by emmalearnscode** [JayantGoel001/JayantGoel001.github.io#15]
### Description

As there are lots of animations on your site, you should add a prefers reduced motion media query so that people can turn off the animations if they have problems with them. Here's some info about it: https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion

**Comment by JayantGoel001** [comment]
@all-contributors please add @emmalearnscode for ideas

**Comment by JayantGoel001** [comment]
@all-contributors please add @emmalearnscode for a11y

**Comment by JayantGoel001** [comment]
> > Hey @emmalearnscode Thanks for letting me know about the above feature(#15). And now it has been implemented 🙌. Feel free to visit again my portfolio and It should work perfectly fine(Remember to clear the cache and then reload ).
> > Thank you.
> 
> Awesome, no problem! I'll take another look when I get time and see how it's going :)

Thanks a lot for sharing your amazing knowledge of accessibility with us.🙂🙂
