### ISSUE TITLE
[BUG]: Nav links aren't links

### ISSUE THREAD

**Issue by emmalearnscode** [JayantGoel001/JayantGoel001.github.io#16]
### Description of the bug

The nav links are not actually links and therefore can't be accessed by keyboard users tabbing through the site.

### Steps To Reproduce

Use the tab button to navigate through the site starting at the URL bar. It jumps from the JAYANT GOEL logo to the download resume button missing out the nav items

**Comment by JayantGoel001** [comment]
Hey @emmalearnscode 
Thanks for letting me know about the above bugs(#16, #17, #18, #19).
But now it has been finally been fixed 🙌.
Feel free to visit again my portfolio and It should work perfectly fine(Remember to clear the cache and then reload ).

Thank you.
