### ISSUE TITLE
[BUG]: Use force in npm install

### ISSUE THREAD

**Issue by NarpatAanjana** [JayantGoel001/JayantGoel001.github.io#45]
### Description

help bro I like it and want to do something edit at my local but as you mention  the npm install command show a lot of error and not working can you do something about it

**Comment by JayantGoel001** [comment]
Hi @NarpatAanjana,
Actually, npm required to use --force to install package successfully  `npm install -f` instead of `npm install`
So, Now It has been fixed you can check once.

Happy Coding😁

**Comment by JayantGoel001** [comment]
@all-contributors please add @NarpatAanjana for bug
